<script>
  import { onDestroy } from 'svelte';
  import { fade } from 'svelte/transition';
  import { preview, hasPreview } from '../stores.js';
  import { createBlobUrl, revokeBlobUrl } from '../lib/previewBuilder.js';

  let iframe;
  let reloadKey = 0;
  let deviceMode = 'desktop'; // desktop, tablet, mobile

  const devices = [
    { id: 'desktop', label: 'Desktop', width: '100%', icon: DesktopIcon },
    { id: 'tablet', label: 'Tablet', width: '768px', icon: TabletIcon },
    { id: 'mobile', label: 'Mobile', width: '375px', icon: MobileIcon },
  ];

  function DesktopIcon(props) {
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${props.size}" height="${props.size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="14" x="2" y="3" rx="2"/><line x1="8" x2="16" y1="21" y2="21"/><line x1="12" x2="12" y1="17" y2="21"/></svg>`;
  }

  function TabletIcon(props) {
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${props.size}" height="${props.size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="16" height="20" x="4" y="2" rx="2" ry="2"/><line x1="12" x2="12.01" y1="18" y2="18"/></svg>`;
  }

  function MobileIcon(props) {
    return `<svg xmlns="http://www.w3.org/2000/svg" width="${props.size}" height="${props.size}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="14" height="20" x="5" y="2" rx="2" ry="2"/><line x1="12" x2="12.01" y1="18" y2="18"/></svg>`;
  }

  function handleReload() {
    reloadKey++;
    if (iframe) {
      iframe.src = iframe.src;
    }
  }

  function handleDeviceChange(device) {
    deviceMode = device;
    preview.update(p => ({ ...p, device }));
  }

  function getSampleHtml() {
    return `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Sample Landing Page</title>
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap" rel="stylesheet">
  <style>
    * { margin: 0; padding: 0; box-sizing: border-box; }
    body { font-family: 'Inter', sans-serif; background: #FAFBFC; color: #0F172A; }
    .hero { min-height: 100vh; display: flex; align-items: center; justify-content: center; text-align: center; padding: 2rem; background: linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%); color: white; }
    .hero h1 { font-size: 3.5rem; font-weight: 700; margin-bottom: 1rem; letter-spacing: -0.02em; }
    .hero p { font-size: 1.25rem; opacity: 0.9; margin-bottom: 2rem; max-width: 600px; }
    .cta { display: inline-flex; align-items: center; gap: 0.5rem; padding: 1rem 2rem; background: white; color: #6366F1; font-weight: 600; border-radius: 12px; text-decoration: none; transition: transform 0.2s, box-shadow 0.2s; }
    .cta:hover { transform: translateY(-2px); box-shadow: 0 8px 24px rgba(0,0,0,0.2); }
    .features { padding: 6rem 2rem; max-width: 1200px; margin: 0 auto; }
    .features h2 { text-align: center; font-size: 2.5rem; margin-bottom: 3rem; }
    .grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 2rem; }
    .card { background: white; padding: 2rem; border-radius: 16px; box-shadow: 0 4px 12px rgba(0,0,0,0.05); transition: transform 0.2s, box-shadow 0.2s; }
    .card:hover { transform: translateY(-4px); box-shadow: 0 12px 28px rgba(0,0,0,0.1); }
    .card-icon { width: 48px; height: 48px; border-radius: 12px; background: linear-gradient(135deg, #6366F1 0%, #8B5CF6 100%); display: flex; align-items: center; justify-content: center; margin-bottom: 1rem; font-size: 1.5rem; }
    .card h3 { font-size: 1.25rem; margin-bottom: 0.5rem; }
    .card p { color: #64748B; line-height: 1.6; }
    .pricing { background: white; padding: 6rem 2rem; }
    .pricing h2 { text-align: center; font-size: 2.5rem; margin-bottom: 3rem; }
    .pricing-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 2rem; max-width: 1000px; margin: 0 auto; }
    .pricing-card { border: 2px solid #E2E8F0; padding: 2rem; border-radius: 16px; text-align: center; }
    .pricing-card.featured { border-color: #6366F1; background: linear-gradient(135deg, rgba(99,102,241,0.05) 0%, rgba(139,92,246,0.05) 100%); }
    .price { font-size: 3rem; font-weight: 700; color: #6366F1; }
    .footer { background: #0F172A; color: white; padding: 3rem 2rem; text-align: center; }
  </style>
</head>
<body>
  <section class="hero">
    <div>
      <h1>Welcome to Your Site</h1>
      <p>This is a sample landing page generated by NEXO. Start chatting to create your own custom design.</p>
      <a href="#" class="cta">Get Started</a>
    </div>
  </section>
  <section class="features">
    <h2>Features</h2>
    <div class="grid">
      <div class="card">
        <div class="card-icon">&#9889;</div>
        <h3>Lightning Fast</h3>
        <p>Optimized performance for the best user experience across all devices.</p>
      </div>
      <div class="card">
        <div class="card-icon">&#127912;</div>
        <h3>Beautiful Design</h3>
        <p>Modern, clean aesthetics that make your brand stand out from the crowd.</p>
      </div>
      <div class="card">
        <div class="card-icon">&#128161;</div>
        <h3>AI-Powered</h3>
        <p>Built with cutting-edge AI to deliver exactly what you envision.</p>
      </div>
    </div>
  </section>
  <section class="pricing">
    <h2>Pricing</h2>
    <div class="pricing-grid">
      <div class="pricing-card">
        <h3>Starter</h3>
        <div class="price">$0</div>
        <p>per month</p>
      </div>
      <div class="pricing-card featured">
        <h3>Pro</h3>
        <div class="price">$29</div>
        <p>per month</p>
      </div>
      <div class="pricing-card">
        <h3>Enterprise</h3>
        <div class="price">$99</div>
        <p>per month</p>
      </div>
    </div>
  </section>
  <footer class="footer">
    <p>Built with NEXO Landing Page Creator</p>
  </footer>
</body>
</html>`;
  }

  $: previewUrl = $preview.blobUrl;
  $: hasContent = $hasPreview;

  // Recreate blob URL if the component is remounted (e.g. switching tabs)
  // without destroying the shared store value.
  $: if ($preview.html && !$preview.blobUrl) {
    preview.update((p) => ({ ...p, blobUrl: createBlobUrl(p.html) }));
  }

  onDestroy(() => {
    // Do NOT revoke the shared blob URL here — it lives in the store so that
    // switching tabs does not break the preview. The store owner is responsible
    // for cleanup when a session is unloaded.
  });
</script>

<div class="flex flex-col h-full bg-luna-surface">
  <!-- Toolbar -->
  <div class="flex-shrink-0 flex items-center justify-between px-4 py-3 bg-white border-b border-luna-border">
    <div class="flex items-center gap-2">
      <span class="text-xs font-semibold text-luna-text-muted uppercase tracking-wider">Preview</span>
      {#if hasContent}
        <span class="px-2 py-0.5 rounded-full bg-emerald-100 text-emerald-700 text-[10px] font-medium">Live</span>
      {/if}
    </div>

    <div class="flex items-center gap-2">
      <!-- Device Toggles -->
      <div class="flex items-center bg-luna-surface rounded-lg p-0.5 border border-luna-border">
        {#each devices as device}
          <button
            class="flex items-center gap-1.5 px-3 py-1.5 rounded-md text-xs font-medium transition-all duration-200"
            class:bg-white={deviceMode === device.id}
            class:text-luna-text={deviceMode === device.id}
            class:shadow-sm={deviceMode === device.id}
            class:text-luna-text-muted={deviceMode !== device.id}
            class:hover:text-luna-text={deviceMode !== device.id}
            on:click={() => handleDeviceChange(device.id)}
            title={device.label}
          >
            <span class="flex items-center justify-center w-3.5 h-3.5">
              {@html device.icon({ size: 14 })}
            </span>
            <span class="hidden sm:inline">{device.label}</span>
          </button>
        {/each}
      </div>

      <!-- Reload Button -->
      <button
        class="flex items-center justify-center w-8 h-8 rounded-lg text-luna-text-muted hover:text-luna-text hover:bg-luna-surface transition-all"
        on:click={handleReload}
        title="Reload preview"
      >
        <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 2v6h-6"/><path d="M3 12a9 9 0 0 1 15-6.7L21 8"/><path d="M3 22v-6h6"/><path d="M21 12a9 9 0 0 1-15 6.7L3 16"/></svg>
      </button>

      <!-- Open in New Tab -->
      {#if previewUrl}
        <a
          href={previewUrl}
          target="_blank"
          rel="noopener noreferrer"
          class="flex items-center justify-center w-8 h-8 rounded-lg text-luna-text-muted hover:text-luna-text hover:bg-luna-surface transition-all"
          title="Open in new tab"
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M15 3h6v6"/><path d="M10 14 21 3"/><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/></svg>
        </a>
      {/if}
    </div>
  </div>

  <!-- Preview Area -->
  <div class="flex-1 overflow-auto p-4 flex items-start justify-center bg-luna-surface">
    {#if hasContent}
      <div
        class="transition-all duration-300 ease-in-out bg-white rounded-xl shadow-md overflow-hidden"
        style="width: {devices.find(d => d.id === deviceMode)?.width || '100%'}; min-height: 600px;"
        in:fade={{ duration: 300 }}
      >
        <iframe
          bind:this={iframe}
          key={reloadKey}
          src={previewUrl}
          title="Landing Page Preview"
          class="w-full h-full border-0"
          style="min-height: 600px;"
          sandbox="allow-scripts allow-same-origin allow-popups allow-forms"
          loading="lazy"
        ></iframe>
      </div>
    {:else}
      <div class="flex flex-col items-center justify-center h-full text-center py-20" in:fade={{ duration: 300 }}>
        <div class="w-20 h-20 rounded-2xl bg-gradient-to-br from-luna-primary/10 to-luna-purple/10 flex items-center justify-center mb-5 animate-float">
          <svg xmlns="http://www.w3.org/2000/svg" width="32" height="32" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round" class="text-luna-primary"><path d="M2 12s3-7 10-7 10 7 10 7-3 7-10 7-10-7-10-7Z"/><circle cx="12" cy="12" r="3"/></svg>
        </div>
        <h3 class="text-lg font-semibold text-luna-text mb-2">No Preview Yet</h3>
        <p class="text-sm text-luna-text-muted max-w-sm mb-6">
          Chat with Luna to generate your landing page. The preview will appear here automatically.
        </p>
        <button
          class="px-4 py-2 rounded-xl btn-primary text-white text-sm font-medium flex items-center gap-2"
          on:click={() => {
            const html = getSampleHtml();
            const blobUrl = createBlobUrl(html);
            preview.set({ html, blobUrl, lastUpdated: Date.now(), device: deviceMode });
          }}
        >
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m12 3-1.912 5.813a2 2 0 0 1-1.275 1.275L3 12l5.813 1.912a2 2 0 0 1 1.275 1.275L12 21l1.912-5.813a2 2 0 0 1 1.275-1.275L21 12l-5.813-1.912a2 2 0 0 1-1.275-1.275L12 3Z"/></svg>
          Load Sample Preview
        </button>
      </div>
    {/if}
  </div>
</div>
